on: [push]

name: Azure_Container_Deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Github Action"
        uses: actions/checkout@master

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: vpwrwedding.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t vpwrwedding.azurecr.io/vprw:${{ github.sha }}
          docker push vpwrwedding.azurecr.io/vprw:${{ github.sha }}

      - uses: azure/webapps-container-deploy@v1
        with:
          app-name: "vprw"
          images: "vpwrwedding.azurecr.io/vprw:${{ github.sha }}"

      - name: Azure logout
        run: |
          az logout
